using KurrentDB.Client;
using Microsoft.Extensions.Logging;
using Microsoft.OpenApi;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace CallbackHandler.Bootstrapper;

using Common;
using Lamar;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using Shared.EventStore.Extensions;
using Shared.General;
using Shared.Middleware;
using Swashbuckle.AspNetCore.Filters;
using System;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Reflection;

[ExcludeFromCodeCoverage]
public class MiddlewareRegistry :ServiceRegistry
{
    public MiddlewareRegistry()
    {
        String connectionString = Startup.Configuration.GetValue<String>("EventStoreSettings:ConnectionString");
        KurrentDBClientSettings eventStoreSettings = KurrentDBClientSettings.Create(connectionString);

        this.AddHealthChecks().AddEventStore(eventStoreSettings, userCredentials: eventStoreSettings.DefaultCredentials,
                                             name: "Eventstore", failureStatus: HealthStatus.Unhealthy, tags: new[] { "db", "eventstore" });

        this.AddSwaggerGen(AddSwaggerAction);
        this.AddSwaggerExamples();

        this.AddControllers();

        Assembly assembly = this.GetType().GetTypeInfo().Assembly;
        this.AddMvcCore().AddApplicationPart(assembly).AddControllersAsServices();

        bool logRequests = ConfigurationReader.GetValueOrDefault<Boolean>("MiddlewareLogging", "LogRequests", true);
        bool logResponses = ConfigurationReader.GetValueOrDefault<Boolean>("MiddlewareLogging", "LogResponses", true);
        LogLevel middlewareLogLevel = ConfigurationReader.GetValueOrDefault<LogLevel>("MiddlewareLogging", "MiddlewareLogLevel", LogLevel.Warning);
        
        this.AddSingleton(new RequestResponseMiddlewareLoggingConfig(middlewareLogLevel, logRequests, logResponses));

        this.ConfigureHttpJsonOptions(jsonOptions => JsonSerializerConfiguration.ConfigureMinimalApi(jsonOptions.SerializerOptions));
    }

    private void AddSwaggerAction(SwaggerGenOptions c) {
        c.SwaggerDoc("v1", new OpenApiInfo { Title = "Callback Handler API", Version = "1.0", Description = "A REST Api to handle callback requests from external parties API's.", Contact = new OpenApiContact { Name = "Stuart Ferguson", Email = "golfhandicapping@btinternet.com" } });
        // add a custom operation filter which sets default values
        c.OperationFilter<SwaggerDefaultValues>();
        c.ExampleFilters();

        //Locate the XML files being generated by ASP.NET...
        DirectoryInfo directory = new(AppContext.BaseDirectory);
        FileInfo[] xmlFiles = directory.GetFiles("*.xml");

        //... and tell Swagger to use those XML comments.
        foreach (FileInfo fileInfo in xmlFiles) {
            c.IncludeXmlComments(fileInfo.FullName);
        }
    }
}
