name: Code Coverage

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
  workflow_dispatch:

jobs:  
  codecoverage:
    name: "Code Coverage"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4  

    - name: Restore Nuget Packages
      run: dotnet restore CallbackHandler.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }}

    - name: Build Code
      run: dotnet build CallbackHandler.sln --configuration Release

    - name: Run Unit Tests
      run: |
        echo "ASPNETCORE_ENVIRONMENT are > ${ASPNETCORE_ENVIRONMENT}"
        mkdir -p coverage/lcov1 coverage/lcov2 coverage/lcov3
        dotnet test "CallbackHandler.BusinessLogic.Tests/CallbackHandler.BusinessLogic.Tests.csproj" --configuration Release --no-build --verbosity normal --coverlet --coverlet-output-format lcov --results-directory "${{ github.workspace }}/coverage/lcov1"
        dotnet test "CallbackHandler.CallbackMessageAggregate.Tests/CallbackHandler.CallbackMessageAggregate.Tests.csproj" --configuration Release --no-build --verbosity normal --coverlet --coverlet-output-format lcov --results-directory "${{ github.workspace }}/coverage/lcov2"
        dotnet test "CallbackHandler.Tests/CallbackHandler.Tests.csproj" --configuration Release --no-build --verbosity normal --coverlet --coverlet-output-format lcov --results-directory "${{ github.workspace }}/coverage/lcov3"

    - name: Install LCOV merger
      run: npm install -g lcov-result-merger

    - name: Merge LCOV reports
      run: |
        lcov-result-merger "coverage/*/coverage.info" > lcov.info

    - name: Upload merged coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./lcov.info      
